# Generated by Django 3.1.7 on 2021-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210521_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienteninfo',
            name='ort',
            field=models.CharField(default='belp', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienteninfo',
            name='plz',
            field=models.CharField(default=34928, max_length=200),
            preserve_default=False,
        ),
    ]
