# Generated by Django 3.1.7 on 2021-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210531_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienteninfo',
            name='plz',
            field=models.IntegerField(),
        ),
    ]
