# Generated by Django 3.1.7 on 2021-11-18 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210531_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(max_length=254, verbose_name='email address')),
                ('email_receiver', models.EmailField(max_length=254, verbose_name='email address')),
                ('location_sender', models.CharField(max_length=50)),
                ('location_receiver', models.CharField(max_length=50)),
                ('address_sender', models.CharField(max_length=50)),
                ('address_receiver', models.CharField(max_length=50)),
                ('city_sender', models.CharField(max_length=50)),
                ('city_receiver', models.CharField(max_length=50)),
                ('zip_sender', models.IntegerField()),
                ('zip_receiver', models.IntegerField()),
                ('state_sender', models.CharField(max_length=50)),
                ('state_receiver', models.CharField(max_length=50)),
                ('number_pallets', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('stackable', models.IntegerField()),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
