# Generated by Django 3.1.7 on 2021-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211120_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='already_optimized',
            field=models.BooleanField(default=False),
        ),
    ]
