# Generated by Django 3.1.7 on 2021-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shippinginfo_already_optimized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='location_receiver',
            new_name='name_receiver',
        ),
        migrations.RenameField(
            model_name='shippinginfo',
            old_name='location_sender',
            new_name='name_sender',
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='cargo_description',
            field=models.CharField(default='spare parts', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='dangerous_goods',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginfo',
            name='loading_meters',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
