# Generated by Django 3.1.7 on 2021-11-21 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211121_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_optimized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(max_length=254, verbose_name='email address')),
                ('email_receiver', models.EmailField(max_length=254, verbose_name='email address')),
                ('email_zwischenstopp', models.EmailField(max_length=254, verbose_name='email address')),
                ('name_sender', models.CharField(max_length=50)),
                ('name_receiver', models.CharField(max_length=50)),
                ('name_zwischenstopp', models.CharField(max_length=50)),
                ('address_sender', models.CharField(max_length=50)),
                ('id_shipping_first', models.IntegerField()),
                ('id_shipping_second', models.IntegerField()),
                ('address_receiver', models.CharField(max_length=50)),
                ('address_zwischenstopp', models.CharField(max_length=50)),
                ('city_sender', models.CharField(max_length=50)),
                ('city_receiver', models.CharField(max_length=50)),
                ('city_zwischenstopp', models.CharField(max_length=50)),
                ('zip_sender', models.IntegerField()),
                ('zip_receiver', models.IntegerField()),
                ('zip_zwischenstopp', models.IntegerField()),
                ('state_sender', models.CharField(max_length=2)),
                ('state_receiver', models.CharField(max_length=2)),
                ('state_zwischenstopp', models.CharField(max_length=2)),
                ('number_pallets', models.IntegerField()),
                ('loading_meters', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dangerous_goods', models.BooleanField()),
                ('cargo_description', models.CharField(max_length=400)),
                ('weight', models.IntegerField()),
                ('stackable', models.IntegerField()),
                ('date_delivery', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude_sender', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('longitude_sender', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('latitude_zwischenstopp', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('longitude_zwischenstopp', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('latitude_receiver', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('longitude_receiver', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
            ],
        ),
    ]
