# Generated by Django 3.1.7 on 2021-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shipping_optimized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_optimized',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
