# Generated by Django 3.1.7 on 2021-11-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211121_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_optimized',
            name='zip_zwischenstopp',
            field=models.IntegerField(null=True),
        ),
    ]
