# Generated by Django 3.1.7 on 2021-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211121_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medikament',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='ref_apotheke_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='ref_arzt_id',
        ),
        migrations.RemoveField(
            model_name='patienteninfo',
            name='arzt',
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='ref_apotheke_id',
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='ref_arzt_id',
        ),
        migrations.DeleteModel(
            name='RezeptMedikamente',
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='cargo_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='number_pallets',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='weight',
            field=models.IntegerField(default=1230),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Patienteninfo',
        ),
        migrations.DeleteModel(
            name='Rezept',
        ),
    ]
