# Generated by Django 3.1.7 on 2021-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='address_receiver',
            field=models.CharField(default='542 W. 15th Street', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='city_receiver',
            field=models.CharField(default='New York', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='dangerous_goods',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='email_receiver',
            field=models.EmailField(default='john@example.com', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='loading_meters',
            field=models.DecimalField(blank=True, decimal_places=3, default=8.4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='name_receiver',
            field=models.CharField(default='John M. Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='number_pallets',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='stackable',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='state_receiver',
            field=models.CharField(default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='weight',
            field=models.IntegerField(blank=True, default=1230, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='zip_receiver',
            field=models.IntegerField(default=10001),
        ),
    ]
